import type { IconName } from "@/components/Icon";

export const SUPPORT_EMAIL = "mail@homedotapp.com";
export const COPYRIGHT = "Copyright @ 2026 HomeDot All Rights Reserved";

export interface TermsSubList {
  items: string[];
}

export interface TermsListItem {
  label?: string;
  text: string;
  sub?: TermsSubList;
}

export interface TermsSection {
  id: string;
  icon: IconName;
  title: string;
  intro?: string[];
  list?: TermsListItem[];
  outro?: string[];
}

// Verbatim from https://homedotapp.com/termsandconditions — section order,
// headings, numbered clauses and wording all mirror the live page exactly
// (the "This document is an electronic record…" opening line is a one-word
// hyphenation fix of the source's "Ment is an electronic record…"); only the
// layout (icons, card chrome, table of contents) is this app's own.
export const TERMS_INTRO: string[] = [
  "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
  "This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.homedotapp.com website and/ or Home Dot mobile application.",
  `By accessing or using the Website/ Application, the Home Dot Service, or any other applications (including mobile applications) made available by Home Dot (together, the "Service"), however accessed, You agree to be bound by these terms of use ("Terms of Use"). The Service is owned and controlled by Home Dot. You are suggested to go through these terms before using Home Dot. These Terms of Use affect Your legal rights and obligations. If You do not agree to be bound by all of these Terms of Use, do not access or use the Service.`,
  `For the purpose of these Terms of Use, wherever the context so requires "You", "Your" or "User" and variants thereof shall mean any natural or legal person who has agreed to become a user of the Service by providing Registration Data while registering on the Service using a computer system. The term "We", "Us", "Our" and variants thereof shall mean Home Dot ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Home Dot policies (including but not limited to Privacy Policy available on Privacy Policy as amended from time to time (together referred to as "Home Dot Policies").`,
  "We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Service following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Service.",
];

export const TERMS_SECTIONS: TermsSection[] = [
  {
    id: "basic-terms",
    icon: "shield",
    title: "Basic Terms",
    list: [
      { label: "Age Requirement:", text: "You must be at least 18 years old and of firm competence to contract to use the Service." },
      {
        label: "User Responsibilities:",
        text: `You are responsible for ensuring that in Your use of the Service, Your action or omission is not contrary to any law for the time being in force. You are not allowed to post violent, discriminatory, plagiarized, promotional, unlawful, infringing, trolling, hateful Content via the Service. For the purposes of clarity, Content refers to any data, text, information, usernames, works of authorship, links and other content or materials, including information that the User posts and/ or uploads on to the service, such as but not limited to the write-ups, photographs, graphics, videos, and any other information formats that may become shareable via the Service from time to time (collectively "Content"). You specifically undertake not to host, display, upload, modify, publish, transmit, update or share any information that –`,
        sub: {
          items: [
            "belongs to another person and to which the user does not have any right to.",
            "is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever.",
            "harms minors in any way.",
            "infringes any patent, trademark, copyright or other proprietary rights.",
            "violates any law for the time being in force.",
            "deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature.",
            "impersonate another person.",
            "contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.",
            "threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.",
          ],
        },
      },
      {
        label: "Breach of Terms:",
        text: "Breach of these Terms of Use on Your part would lead to a removal of any and all of Your Content and revoke Your posting rights. Repeated breach will lead to a permanent account ban, and You may not be permitted to access the Service ever again.",
      },
      {
        label: "Account Responsibility:",
        text: `You are responsible for any activity that occurs through Your account and You agree You will not sell, transfer, licence or assign Your account, followers, username, or any account rights. With the exception of people or businesses that are expressly authorised to create accounts on behalf of their employers or clients, Home Dot prohibits the creation of and You agree that You will not create an account for anyone other than Yourself. You also represent that all information You provide or provided to Home Dot upon registration ("Registration Data") and at all other times will be true, accurate, current and complete and You agree to update Your information as necessary to maintain its truth and accuracy.`,
      },
      {
        label: "Electronic Communication:",
        text: "When You use the Service or other data, information or communication to Us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with You by email or by such other modes of communication, electronic or otherwise.",
      },
      {
        label: "Prohibition on Credential Collection:",
        text: "You agree that You will not solicit, collect or use the login credentials of other Home Dot Users.",
      },
      { label: "Account Security:", text: "You must take responsibility for keeping Your username and OTP safe and secure." },
      {
        label: "Privacy and Discretion:",
        text: "You must not post private or confidential information via the Service, including, without limitation, Your or any other person's credit card information, social security or alternate national identity numbers, non-public phone numbers or non-public email addresses. You are requested to maintain discretion before adding users on other social networking platforms or sharing phone numbers. Home Dot shall not be responsible for any harassment the User suffers from other users on the Service, or any other platform(s). Please approach the support of those platforms and use the block feature on Home Dot to disable them from interacting with You. You are responsible for any post related to self-harm that You post on the Service. Home Dot is not liable for any injury or damage that occurs either before, during or after Your use of the Service.",
      },
      {
        label: "Prohibited Use:",
        text: "You may not use the Service for any illegal or unauthorised purpose. You agree to comply with all laws, rules and regulations applicable to Your use of the Service and Your Content, including but not limited to, copyright laws.",
      },
      { label: "User Conduct and Content:", text: "You are solely responsible for Your conduct and Content that You post on Home Dot." },
      {
        label: "Modification and Misrepresentation:",
        text: "You must not change, modify, adapt or alter the Service or change, modify or alter another website so as to falsely imply that it is associated with the Service or not modify or alter the Service or modify another website so as to falsely imply that it is associated with Home Dot.",
      },
      {
        label: "Disruption and Malicious Activity:",
        text: "You must not interfere or disrupt the Service or servers/networks connected to the Service, including by transmitting worms, viruses, spyware and malware or any other code that is destructive or disruptive in nature. Interfering with the display of any Home Dot's page in a User's browser or device is illegal.",
      },
      {
        label: "Unauthorized Account Creation:",
        text: "You shall not create accounts on Home Dot using unauthorised means, including but not limited to, by using an automated device, script, bot, spider, crawler or scraper is not allowed.",
      },
      {
        label: "Content Distribution Rights:",
        text: "Home Dot reserves the right to distribute Your Content posted on Home Dot through its social media handles, with due credits to the User.",
      },
      {
        label: "Respect for Others:",
        text: "You must not attempt to restrict another user from using or enjoying the Service and You must not encourage or facilitate violations of these Terms of Use or any other Home Dot Policies.",
      },
      {
        label: "Enforcement and Termination:",
        text: "Violation of these Terms of Use may, in Home Dot's sole discretion, result in termination of Your Home Dot account. We are not responsible for any Content that is posted on Home Dot. If You violate the Terms of Use, or create risk/possible legal exposure for Home Dot, we can stop providing all or part of the Service to You.",
      },
    ],
  },
  {
    id: "general-terms",
    icon: "settings",
    title: "General Terms",
    list: [
      {
        label: "Service Termination:",
        text: "Home Dot reserves the right to alter or terminate the Service or Your access to the Service for any reason, without notice, at any time, and without any liability to You. You can deactivate Your Home Dot account at your discretion. If We terminate Your access to the Service or You delete Your account, Your Content, including work, comments, likes, friendships, and all other data will not be accessible to anyone (e.g., Users will not be able to navigate to Your username and view Your work). However, we may archive certain information, including Personal Information, and retain it as we may be required to do in order to fulfil our legal obligations.",
      },
      {
        label: "Updates to Terms:",
        text: `Home Dot reserves the right, in our sole discretion, to change these Terms of Use ("Updated Terms'') from time to time. We may notify You before the Updated Terms become effective. You should review these updated Terms of Use prior to using Home Dot. The Updated Terms will take effect from the time it is updated, or from sometime later as mentioned in the update. These Terms of Use will govern any disputes arising prior to the effective date of the Updated Terms.`,
      },
      {
        label: "Access Denial:",
        text: "Home Dot reserves the right to deny access to the Service to any User for any reason at any time. We may remove, edit, and/or monitor content or accounts we believe violate these Terms of Use.",
      },
      { label: "Account Forfeiture:", text: "Home Dot reserves the right to force forfeiture of any username, profile or account for any reason at any time." },
      {
        label: "User Conduct Responsibility:",
        text: "Home Dot is not responsible or liable for the conduct of any of its Users, be it online or offline. You will be responsible for Your interactions with other Home Dot users on or off the Service. We reserve the right but we are not obliged to monitor or get involved in disputes between You and other users. A User should use his common sense and best judgement while interacting with other Home Dot users.",
      },
      { label: "Third-Party Dealings:", text: "Your business dealings with third parties found on Home Dot are solely between You and the third parties." },
      { label: "Data Charges:", text: "You take responsibility for any and all data charges that incur on using Home Dot." },
      {
        label: "Automated Access Restriction:",
        text: "We prohibit crawling, scraping, caching or otherwise accessing any Content on the Service via automated means, including but not limited to, user profiles and photos (except as may be the result of standard search engine protocols or technologies used by a search engine with Home Dot's express written consent).",
      },
      {
        label: "Jurisdiction:",
        text: "You further undertake to submit to the jurisdiction of courts at Bengaluru for any action arising from the breach of these Terms of Use, other Home Dot Policies, violation of the IT Act and/ or other laws, pursuant to Your usage or access of the Service.",
      },
    ],
  },
  {
    id: "rights",
    icon: "verified",
    title: "Rights",
    list: [
      {
        label: "Content Ownership & License:",
        text: "Home Dot does not claim ownership of any Content that a User posts on the Service. Instead, You hereby grant to Home Dot a non-exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide licence to use the Content that You post on or through the Service, subject to the Service's Privacy Policy, available at Terms of Service.",
      },
      {
        label: "Content Rights:",
        text: "You agree that: –",
        sub: {
          items: [
            "You own the Content posted by You on Home Dot or otherwise have the right to grant the right/licences for it as set forth in these Terms of Use;",
            "Your Content must not infringe on the rights of other Users, including, without limiting to privacy and publicity rights, copyrights/trademark and/or other intellectual property rights.",
          ],
        },
      },
      {
        label: "Home Dot Intellectual Property:",
        text: `Home Dot has content that is owned by Home Dot ("Home Dot Content'') and is protected by copyright, trademark, patent, and other relevant laws. You will not modify, remove or conceal any copyright, trademark, service mark or any other proprietary rights notice that accompanies Home Dot Content. You will not reproduce, modify, adapt, prepare derivative works based on, display, distribute, publish, transmit, sell, licence or otherwise exploit the Home Dot Content.`,
      },
      {
        label: "Trademarks and Branding:",
        text: "Home Dot's name and logo are trademarks of Home Dot, and must not be copied, or used, in whole or in part, without our prior written permission. In addition, custom graphics, all page headers, button icons and scripts are service marks, trademarks and/or trade dress of Home Dot, and must not be copied or used, in whole or in part, without prior written permission from Home Dot.",
      },
      {
        label: "Service Interruption & Content Backup:",
        text: "The Service may be interrupted for upgrades or scheduled maintenance, for emergency repairs, or due to failure of telecommunications links and/or equipment. Home Dot reserves the right to remove Your Content from the Service without any reason, without any prior notice to You. Content removed from Home Dot may be stored by us, but may not be accessed by You without a valid court order. Home Dot encourages You to maintain Your own backup of Your Content. We are not a backup Service and You will not rely on us for the purpose of Content backup or storage. We will not be liable for suspension, modification or discontinuation of Service, or any loss of Content. You also acknowledge the fact that Internet may be subject to security breaches and that the submission of Content or other information may not be secure.",
      },
      {
        label: "Content Responsibility & Indemnification:",
        text: "You agree that We are not responsible for, and do not endorse any Content posted on Home Dot. Home Dot does not have any obligation to monitor, prescreen, edit, or remove any Content. If Your Content violates these Terms of Use, You may bear legal responsibility for it. By accepting these Terms of Use and using Home Dot, You agree to indemnify, save, and hold Us, the company, its affiliates, contractors, employees, officers, directors, agents and its third party suppliers, licensors, and partners harmless from any and all claims, losses, damages, and liabilities, costs and expenses, including without limitation legal fees and expenses, arising out of or related to Your use or misuse of the Services or of Home Dot, any violation by You of these Terms of Use, or any breach of the representations, warranties, and covenants made by You herein. We reserve the right, at Your expense, to assume the exclusive defence and control of any matter for which You are required to indemnify Us, the Company, including rights to settle, and You agree to cooperate with Our defence and settlement of these claims. We will use reasonable efforts to notify You of any claim, action, or proceeding brought by a third party that is subject to the foregoing indemnification upon becoming aware of it. This paragraph shall survive termination of Your acceptance of these Terms of Use.",
      },
      {
        label: "Non-Confidentiality:",
        text: "All Content posted by the Users will be non-confidential and non-proprietary. We will not be liable for any use or disclosure of any Content that You provide.",
      },
    ],
  },
  {
    id: "electronic-communications",
    icon: "mail",
    title: "Electronic Communications",
    list: [
      {
        text: "You acknowledge and understand that:",
        sub: {
          items: [
            "You are accessing the Site and using the Services via the Internet, and therefore you consent to receiving Communications electronically.",
            "This section informs you of your rights when receiving Communications from us electronically.",
          ],
        },
      },
      {
        text: "For contractual purposes, you:",
        sub: {
          items: [
            "Consent to receive communications from us in electronic form.",
            `Agree that all terms, agreements, notices, disclosures, and other communications ("Communications") that we provide electronically satisfy any legal requirement that such Communications would satisfy if they were in writing.`,
          ],
        },
      },
    ],
    outro: [
      "Your consent to receive Communications and conduct business electronically applies to all interactions and transactions with Home Dot. You further agree to receive all service communications from Home Dot electronically.",
    ],
  },
  {
    id: "reporting-infringements",
    icon: "trash",
    title: "Reporting Copyrights/IP Infringements",
    list: [
      { label: "Reporting Infringement:", text: "You can report posts to protect Your intellectual property rights." },
      { label: "Enforcement Against Infringement:", text: "If You are caught in the act of infringing on others Content, we will disable Your account." },
    ],
  },
  {
    id: "disclaimer",
    icon: "close",
    title: "Disclaimer of Warranties",
    list: [
      {
        text: `The service, including, without limitation, Home Dot content, is provided on an "as is", "as available" and "with all faults" basis. To the fullest extent permissible by law, neither Home Dot nor any of their employees, managers, officers or agents (collectively, the "Home Dot parties") make any representations or warranties or endorsements of any kind whatsoever, express or implied, as to:`,
        sub: { items: ["the service;", "the Home Dot content;", "user content; or", "security associated with the transmission of information to Home Dot or via the service."] },
      },
    ],
    outro: [
      "In addition, the Home Dot parties hereby disclaim all warranties, express or implied, including, but not limited to, the warranties of merchantability, fitness for a particular purpose, non-infringement, title, custom, trade, quiet enjoyment, system integration and freedom from computer virus.",
      "The Home Dot parties do not represent or warrant that the service will be error-free or uninterrupted; that defects will be corrected; or that the service or the server that makes the service available is free from any harmful components, including, without limitation, viruses. The Home Dot parties do not make any representations or warranties that the information (including any instructions) on the service is accurate, complete, or useful. You acknowledge that your use of the service is at your sole risk. Home Dot do not warrant that your use of the service is lawful in any particular jurisdiction, and the Home Dot parties specifically disclaim such warranties. Some jurisdictions limit or do not allow the disclaimer of implied or other warranties so the above disclaimer may not apply to you to the extent such jurisdiction's law is applicable to you and these terms of use.",
      "By accessing or using the service you represent and warrant that your activities are lawful in every jurisdiction where you access or use the service.",
      "Home Dot do not endorse content and specifically disclaim any responsibility or liability to any person or entity for any loss, damage (whether actual, consequential, punitive or otherwise), injury, claim, liability or other cause of any kind or character based upon or resulting from any content.",
    ],
  },
  {
    id: "limitation-of-liability",
    icon: "hardhat",
    title: "Limitation of liability, waiver",
    list: [
      {
        text: "Under no circumstances will Home Dot parties be liable to you for any loss or damages of any kind (including, without limitation, for any direct, indirect, economic, exemplary, special, punitive, incidental or consequential losses or damages) that are directly or indirectly related to:",
        sub: {
          items: [
            "The service;",
            "The Home Dot content",
            "User content",
            "Your use of, inability to use, or the performance of the service;",
            "any action taken in connection with an investigation by Home Dot parties or law enforcement authorities regarding your or any other party's use of the service;",
            "any action taken in connection with copyright or other intellectual property owners;",
            "any errors or omissions in the service's operation; or",
            "any damage to any user's computer, mobile device, or other equipment or technology including, without limitation, damage from any security breach or from any virus, bugs, tampering, fraud, error, omission, interruption, defect, delay in operation or transmission, computer line or network failure or any other technical or other malfunction, including, without limitation, damages for lost profits, loss of goodwill, loss of data, work stoppage, accuracy of results, or computer failure or malfunction, even if foreseeable or even if Home Dot has been advised of or should have known of the possibility of such damages, whether in an action of contract, negligence, strict liability or tort (including, without limitation, whether caused in whole or in part by negligence, acts of God, telecommunications failure, or theft or destruction of the service).",
          ],
        },
      },
    ],
    outro: [
      "In no event will Home Dot be liable to you or anyone else for loss, damage or injury, including, without limitation, death or personal injury. Some states do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. You agree that in the event you incur any damages, losses or injuries that arise out of Home Dot's acts or omissions, the damages, if any, caused to you are not irreparable or sufficient to entitle you to an injunction preventing any exploitation of any website, service, property, product or other content owned or controlled by Home Dot, and you will have no rights to enjoin or restrain the development, production, distribution, advertising, exhibition or exploitation of any website, property, product, service, or other content owned or controlled by Home Dot.",
      "Home Dot is not responsible for the actions, content, information, or data of third parties, and you release us, our directors, officers, employees, and agents from any claims and damages, known and unknown, arising out of or in any way connected with any claim you have against any such third parties.",
    ],
  },
  {
    id: "grievances",
    icon: "phone",
    title: "Grievances",
    list: [
      {
        text: `If you wish to register a complaint regarding X, you may do so by sending an email to ${SUPPORT_EMAIL}. Your email will be acknowledged by a system generated response, or via an individual manual email to the extent possible, within 24 hours of us having received it. You will be kept informed of the progress we make in redressing your complaint and/ or the reasons for delay, if any, in such redressal. Email Id: ${SUPPORT_EMAIL}`,
      },
    ],
  },
];
